learning_templates/basicapp/urls.py
from django.urls import path
from basicapp import views

app_name='basicapp'

urlpatterns=[
    path('relative/',views.relative,name='relative'),
    path('other/',views.other,name='other'),
    path('base/',views.base,name='base'),
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path
from basicapp import views
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('basicapp/',include('basicapp.urls'))
]

learning_templates/basicapp/models.py
from django.db import models

# Create your models here.

learning_templates/basicapp/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict={'text':'hello world','number':100}
    return render(request,'basicapp/index.html',context_dict)

def other(request):
    return render(request,'basicapp/other.html')


def relative(request):
    return render(request,'basicapp/relataive_url_templates.html')

def base(request):
    return render(request,'basicapp/base.html')

learning_templates/templates/basicapp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li ><a class="navbar-brand" href="{%url 'index'%}">BRAND</a></li>
          <li><a class="navbar-link" href="{%url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{%url 'basicapp:other'%}">Other</a></li>
        </ul>
      </div>
    </nav>
    <div class="container">
      {% block body_block %}
      <!-- anything -->
      {% endblock %}
    </div>
  </body>
</html>

learning_templates/templates/basicapp/index.html
<!DOCTYPE html>
{% extends "basicapp/base.html"%}
  {% block body_block %}
    <h1>WELCOME TO INDEX!</h1>
    <h1>{{text|cut:'world'}}</h1>
    <h1>{{number|add:'99'}}</h1>
  {% endblock %}

learning_templates/templates/basicapp/other.html
<!DOCTYPE html>
{% extends "basicapp/base.html"%}
  {% block body_block %}
    <h1>WELCOME TO OTHER!</h1>
    <h2>This is an example of template inheritance!</h2>
  {% endblock %}

learning_templates/templates/basicapp/relataive_url_templates.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  </head>
  <body>
    <div class="container">
      <div class="jumbotron">

      <h1>WELCOME TO RELATIVE TEMPLATES!</h1>
      <h2>HOPE YOU ARE ENJOYING</h2>

      <a href="{% url 'basicapp:other' %}">The other page</a><br>
      <a href="{% url 'index' %}">The index page</a>
</div>
    </div>
  </body>
</html>